---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mysql
      version: 8.8.19  
      sourceRef:
        kind: HelmRepository
        name: bitnami  
  interval: 30s
  releaseName: mysql

